name: isotope_workcell

include:
  - path: 'docker/wei.compose.yaml'
    project_directory: '.'
    env_file: '.env'

services:
  mir_node:
    image: ghcr.io/ad-sdl/mir_module:dev
    container_name: mir_node
    privileged : true
    command: python -m mir_rest_node --port 2000
    ports:
      - 2000:2000
    env_file:
      - .env
  # ur_node:
  #   image: ghcr.io/ad-sdl/ur_module
  #   container_name: ur_node
  #   privileged: true 
  #   ports:
  #     - 2001:2001
  #   command: python -m camera_rest_node --port 2001
  #   env_file:
  #     - .env
