name: isotope_workcell

include:
  - path: 'docker/wei.compose.yaml'
    project_directory: '.'
    env_file: '.env'

services:
  mir_node:
    image: ghcr.io/ad-sdl/mir_module:aileen_dev
    container_name: mir_node
    privileged : true
    command: python -m mir_rest_node --port 2000
    ports:
      - 2000:2000
    env_file:
      - .env
  ur_node:
    image: ghcr.io/ad-sdl/ur_module:latest
    container_name: ur_node
    privileged: true 
    ports:
      - 2001:2001
    command: python -m ur_rest_node --port 2001 --ur_ip ${UR_IP}
    env_file:
      - .env
